name: tests
on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          set -eux
          python -m pip install -U pip wheel
          # Install test dependencies (always)
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            python -m pip install pytest pyyaml openpyxl openapi-spec-validator
          fi
          # Install the project (editable if packaging files exist)
          if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f setup.cfg ]; then
            python -m pip install -e .
          fi
          # Sanity check: ensure pytest is present
          python -m pip show pytest

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}   # fallback if not installed as a package
        run: python -m pytest -q
