name: tests
on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            python -m pip install pytest pyyaml openpyxl openapi-spec-validator
          fi
          # Install your package if packaging files exist; otherwise we'll set PYTHONPATH later
          if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f setup.cfg ]; then
            python -m pip install -e .
          fi

      - name: Sanity print (env + files)
        run: |
          python -V
          pip --version
          pip freeze | sed -n '1,120p'
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          ls -la tests || true
          ls -la tests/data || true

      - name: Run tests
        env:
          # Fallback so imports like `from api_description_tool import ...` work without packaging install
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q
