- name: Install deps
  run: |
    python -m pip install -U pip
    python -m pip install -r requirements-dev.txt
    # install your package in editable mode if you have packaging files
    if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f setup.cfg ]; then python -m pip install -e .; fi